library(data.table)
library(dplyr)
library(tidyr)
library(lubridate)
epcdata<-read.table("household_power_consumption.txt",header = TRUE,sep = ";",stringsAsFactors = FALSE, na.strings = "?",)
febdata<-subset(epcdata, Date %in% c("1/2/2007", "2/2/2007"))
str(febdata)
febdata$Date<- as.Date(febdata$Date, format="%d/%m/%Y")
head(febdata$Date)
DateTime <- paste(as.Date(febdata$Date),febdata$Time)
febdata$DateTime<-as.POSIXct(DateTime)
head(febdata$DateTime)
str(febdata)

##plot3
png("plot3.png", width=480, height=480)
with(febdata, plot(DateTime,Sub_metering_1, type="l",ylab="Energy sub metering", xlab=""))
with(febdata,lines(DateTime,Sub_metering_2,col='red'))
with(febdata, lines(DateTime,Sub_metering_3,col='blue'))
legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2,legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()
